### ISSUE TITLE
Scroll and Stop vs. Flinging

### ISSUE THREAD

**Issue by fxsalazar** [Trinea/android-auto-scroll-view-pager#15]
When trying to scroll and stop to the left (contrary to flingin) the pager moves 1 page on the opposite side, if not to the other. It's an strange behavior. Could you pleas take a look at it.

**Comment by Trinea** [comment]
Sorry, there is some bug with setSlideBorderMode (SLIDE_BORDER_MODE_CYCLE), and i don't have time to fix it.

**Comment by fxsalazar** [comment]
I will be glad to help on it. If you can give some inputs on where exactly is the issue or what do you think it could be...

**Comment by Trinea** [comment]
my be some bug in onTouchEvent function
