### ISSUE TITLE
app:dexDebug错误

### ISSUE THREAD

**Issue by kingaza** [Trinea/android-auto-scroll-view-pager#22]
遇到这么一个错误
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 2

不过不知道跟别的哪个库有冲突了
这是我的gradle.build
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // Google stuff
    compile 'com.android.support:appcompat-v7:22.1.0'

    // Square-y stuff
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup:otto:1.3.5'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'cn.trinea.android.view.autoscrollviewpager:android-auto-scroll-view-pager:1.1.2'
    compile 'com.squareup.dagger:dagger:1.2.1'
    provided 'com.squareup.dagger:dagger-compiler:1.2.1'

    // UI stuff
    compile 'com.jakewharton:butterknife:5.1.2'
    compile 'com.nispok:snackbar:2.7.5'
    compile 'com.marshalchen.ultimaterecyclerview:library:0.3.6'
    compile 'com.github.lecho:hellocharts-library:1.5.5@aar'

    // Unit tests
    testCompile 'com.android.support.test:testing-support-lib:0.1'
    testCompile 'org.mockito:mockito-core:1.9.0'
}

**Comment by kingaza** [comment]
知道为啥了。。。
v4的支持库。直接用代码就解决了

**Comment by Trinea** [comment]
ok，等闲下来我会把这个问题解决
