### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by whinc** [Trinea/android-auto-scroll-view-pager#24]
我现在有个需求,自动播放时速度放慢,手动切换时速度使用正常速度,现在通过`setScrollDurationFactor()`设置一个较慢的切换速度,可是手动滑动时速度也很慢了,可不可以暴露个监听接口,监听自动和手动模式的切换事件,这样可以设置不同模式下的ViewPager切换速度.

**Comment by whinc** [comment]
不要意思原来有这样的接口`setAutoScrollDurationFactor()`和`setSwipeScrollDurationFactor()`,不过是在源码中,使用 Maven 库导入的jar包中不包含这两个接口,请更新一下MAVEN库

**Comment by whinc** [comment]
Readme 中的 Maven 坐标还是 1.1.2 版本,好像没有更新

**Comment by Trinea** [comment]
抱歉暂时没时间更新呢，可以自己拉源码编译为一个 jar

**Comment by whinc** [comment]
嗯，谢谢~！
