### ISSUE TITLE
don't consume touch event when scroll up or down

### ISSUE THREAD

**Issue by AmirHadifar** [Trinea/android-auto-scroll-view-pager#29]
Hi , first Thanks for your library. 

I want to put **auto-scroll-view-pager** as header of my listview (RecyclerView) but When I scroll up/down it consume touch event. I use following piece of code to handle this issue (I put it in dispatchTouchEvent method ):

```

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        int action = MotionEventCompat.getActionMasked(ev);

        if (stopScrollWhenTouch) {
            if ((action == MotionEvent.ACTION_DOWN) && isAutoScroll) {
                isStopByTouch = true;
                stopAutoScroll();
            } else if (ev.getAction() == MotionEvent.ACTION_UP && isStopByTouch) {
                startAutoScroll();
            }
        }

        if (slideBorderMode == SLIDE_BORDER_MODE_TO_PARENT || slideBorderMode == SLIDE_BORDER_MODE_CYCLE) {
            touchX = ev.getX();
            if (ev.getAction() == MotionEvent.ACTION_DOWN) {
                downX = touchX;
            }
            int currentItem = getCurrentItem();
            PagerAdapter adapter = getAdapter();
            int pageCount = adapter == null ? 0 : adapter.getCount();
            /**
             * current index is first one and slide to right or current index is last one and slide to left.<br/>
             * if slide border mode is to parent, then requestDisallowInterceptTouchEvent false.<br/>
             * else scroll to last one when current item is first one, scroll to first one when current item is last
             * one.
             */
            if ((currentItem == 0 && downX <= touchX) || (currentItem == pageCount - 1 && downX >= touchX)) {
                if (slideBorderMode == SLIDE_BORDER_MODE_TO_PARENT) {
                    getParent().requestDisallowInterceptTouchEvent(false);
                } else {
                    if (pageCount > 1) {
                        setCurrentItem(pageCount - currentItem - 1, isBorderAnimation);
                    }
                    getParent().requestDisallowInterceptTouchEvent(true);
                }
                return super.dispatchTouchEvent(ev);
            }
        }
       //----------------this is my code ----------------
        boolean consumeTouch = false;
        if (action == MotionEvent.ACTION_DOWN) {
            touchY = ev.getY();
        } else if (action == MotionEvent.ACTION_UP) {
            consumeTouch = Math.abs(touchY - ev.getY()) > 0;
        }
        if (consumeTouch)
            getParent().requestDisallowInterceptTouchEvent(true);
        else
            getParent().requestDisallowInterceptTouchEvent(false);


        return super.dispatchTouchEvent(ev);
    }
```

It's work somehow but have issue. When I scroll up/down autoScroll mode not worked. Can you help me to solve this issue ?

**Comment by youfacepalm** [comment]
Would love a solution tho this

**Comment by youfacepalm** [comment]
After fiddling with the code for a while I was able to fix the issue like the following. This is based on @AmirHadifar 's solution

        boolean consumeTouch = false;
        if (action == MotionEvent.ACTION_DOWN) {
            touchY = ev.getY();
        } else if (action == MotionEvent.ACTION_UP) {
            consumeTouch = Math.abs(touchY - ev.getY()) > 0;
        }

        if (consumeTouch) {
            getParent().requestDisallowInterceptTouchEvent(true);
        } else {
            getParent().requestDisallowInterceptTouchEvent(false);
            if(stopScrollWhenTouch)
                startAutoScroll();
        }

**Comment by amanzan** [comment]
@youfacepalm where exactly goes your code? I have the same issue

**Comment by amanzan** [comment]
Replace dispatchTouchEvent method by this:

`@Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        int action = MotionEventCompat.getActionMasked(ev);
        if (stopWhenTouch) {
            switch (action) {
                case MotionEvent.ACTION_DOWN:
                    if (isAutoScroll) {
                        isStopedWhenTouch = true;
                        stopAutoScroll();
                    }
                    break;
                case MotionEvent.ACTION_UP:
                case MotionEvent.ACTION_OUTSIDE:
                    if (isStopedWhenTouch) {
                        startAutoScroll();
                    }
                    break;
            }
        }
        return super.dispatchTouchEvent(ev);
    }
`

**Comment by ashokbg** [comment]
@amanzan suggestion worked ..    

`@Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        int action = MotionEventCompat.getActionMasked(ev);
        if (stopWhenTouch) {
            switch (action) {
                case MotionEvent.ACTION_DOWN:
                    if (isAutoScroll) {
                        isStopedWhenTouch = true;
                        stopAutoScroll();
                    }
                    break;
                case MotionEvent.ACTION_UP:
                case MotionEvent.ACTION_OUTSIDE:
                    if (isStopedWhenTouch) {
                        startAutoScroll();
                    }
                    break;
            }
        }
        return super.dispatchTouchEvent(ev);
    }
