### ISSUE TITLE
show two or more images in a page

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [Trinea/android-auto-scroll-view-pager#35]
Hello
Is it possible to show two or more images in a page Simultaneously.
I want to implement this for tablet size devices.

![preview](https://cloud.githubusercontent.com/assets/15226836/23707257/f14a2fcc-0426-11e7-8c08-34a786457e03.png)

**Comment by Trinea** [comment]
You can implements this by design your own fragment for viewpager
