### ISSUE TITLE
Vertical Scroll not working inside scrollview

### ISSUE THREAD

**Issue by akslive** [Trinea/android-auto-scroll-view-pager#37]
when view pager is added in a scrollview and try to scroll vertically on dragging over view pager not works, one has to vertical scroll below view pager to scroll down.

**Comment by akslive** [comment]
duplicate of #29

**Comment by RaylanXL** [comment]
hello, How do you solve this problem? I cannot scroll vertically when I  used it in a scrollView. But it can scroll normally in a recyclerView.
